# Generated by Django 3.2.5 on 2021-08-07 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30)),
                ('created_by', models.CharField(max_length=25)),
                ('completed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todoapp.completed')),
            ],
        ),
    ]
